<Contador>:

    BoxLayout:
        orientation: 'vertical'
        BoxLayout:
            Button:
                text: '+'
                font_size: 30
                on_release: label.text = str(int(label.text) + 1)

            Button:
                text: '-'
                font_size: 30
                on_release: label.text = str(int(label.text) - 1)

        BoxLayout:
            Label:
                id: label
                text:'1'
                font_size: 30
